# Generated by Django 6.0.2 on 2026-03-17 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_bill_state_bill_tracker_bil_state_d8ee96_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('abbreviation', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Parties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, help_text="State code (e.g., 'UP', 'DL')", max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the MP', max_length=200)),
                ('constituency', models.CharField(help_text='Parliamentary constituency', max_length=200)),
                ('house', models.CharField(choices=[('LOK_SABHA', 'Lok Sabha'), ('RAJYA_SABHA', 'Rajya Sabha')], max_length=20)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mps', to='tracker.party')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mps', to='tracker.state')),
            ],
            options={
                'verbose_name': 'MP',
                'verbose_name_plural': 'MPs',
                'ordering': ['state', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the MLA', max_length=200)),
                ('constituency', models.CharField(help_text='Assembly constituency', max_length=200)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mlas', to='tracker.party')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mlas', to='tracker.state')),
            ],
            options={
                'verbose_name': 'MLA',
                'verbose_name_plural': 'MLAs',
                'ordering': ['state', 'name'],
            },
        ),
    ]
