# Generated by Django 6.0.2 on 2026-03-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_party_state_mp_mla'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mla',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mp',
            options={},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={},
        ),
        migrations.AlterField(
            model_name='mla',
            name='constituency',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mla',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mp',
            name='constituency',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mp',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='state',
            name='code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
