# Generated by Django 4.2.7 on 2026-04-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_mla_options_alter_mp_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='passed_in_ls_date',
            field=models.DateField(blank=True, null=True, verbose_name='Passed in Lok Sabha'),
        ),
        migrations.AddField(
            model_name='bill',
            name='passed_in_rs_date',
            field=models.DateField(blank=True, null=True, verbose_name='Passed in Rajya Sabha'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['passed_in_ls_date'], name='tracker_bil_passed__d9db45_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['passed_in_rs_date'], name='tracker_bil_passed__8a0eb7_idx'),
        ),
    ]
