# Generated by Django 4.2.7 on 2026-04-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_bill_passed_in_ls_date_bill_passed_in_rs_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='act_number',
            field=models.CharField(blank=True, help_text='Act number after presidential assent', max_length=50),
        ),
        migrations.AddField(
            model_name='bill',
            name='act_year',
            field=models.IntegerField(blank=True, help_text='Year when bill became act', null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='assent_date',
            field=models.DateField(blank=True, null=True, verbose_name='Presidential Assent Date'),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('GOVERNMENT', 'Government Bill'), ('PRIVATE', 'Private Member Bill'), ('FINANCE', 'Finance Bill'), ('CONSTITUTION', 'Constitution Amendment Bill')], help_text='Government/Private Bill', max_length=50),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_url',
            field=models.URLField(blank=True, help_text='Official bill page URL', max_length=500),
        ),
        migrations.AddField(
            model_name='bill',
            name='committee_name',
            field=models.CharField(blank=True, help_text='Name of the committee', max_length=500),
        ),
        migrations.AddField(
            model_name='bill',
            name='committee_report_date',
            field=models.DateField(blank=True, help_text='Date of committee report', null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='debated_on_ls_date',
            field=models.DateField(blank=True, null=True, verbose_name='Debated/Passed in Lok Sabha'),
        ),
        migrations.AddField(
            model_name='bill',
            name='debated_on_rs_date',
            field=models.DateField(blank=True, null=True, verbose_name='Debated/Passed in Rajya Sabha'),
        ),
        migrations.AddField(
            model_name='bill',
            name='gazette_notification_date',
            field=models.DateField(blank=True, null=True, verbose_name='Gazette Notification Date'),
        ),
        migrations.AddField(
            model_name='bill',
            name='gazette_notification_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Gazette Notification Number'),
        ),
        migrations.AddField(
            model_name='bill',
            name='legislative_year',
            field=models.IntegerField(blank=True, help_text='Year of introduction', null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='originating_house',
            field=models.CharField(blank=True, choices=[('LOK_SABHA', 'Lok Sabha'), ('RAJYA_SABHA', 'Rajya Sabha')], help_text='House where bill was first introduced', max_length=20),
        ),
        migrations.AddField(
            model_name='bill',
            name='referred_to_committee',
            field=models.BooleanField(default=False, help_text='Referred to parliamentary committee'),
        ),
        migrations.AddField(
            model_name='bill',
            name='status_history',
            field=models.JSONField(blank=True, default=list, help_text='Historical status changes'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('LAPSED', 'Lapsed'), ('ENACTED', 'Enacted')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='scrapesource',
            name='source_type',
            field=models.CharField(choices=[('PRS', 'PRS India'), ('LOK_SABHA', 'Lok Sabha'), ('RAJYA_SABHA', 'Rajya Sabha'), ('DATA_GOV_IN', 'data.gov.in'), ('MPA', 'Ministry of Parliamentary Affairs')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['assent_date'], name='tracker_bil_assent__ca0663_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['originating_house'], name='tracker_bil_origina_d2f147_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['legislative_year'], name='tracker_bil_legisla_5ca606_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['debated_on_ls_date'], name='tracker_bil_debated_932acb_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['debated_on_rs_date'], name='tracker_bil_debated_235c8c_idx'),
        ),
    ]
