# Generated by Django 4.2.7 on 2026-04-25 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_bill_act_number_bill_act_year_bill_assent_date_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bill',
            name='tracker_bil_origina_d2f147_idx',
        ),
        migrations.RemoveIndex(
            model_name='bill',
            name='tracker_bil_legisla_5ca606_idx',
        ),
        migrations.RemoveIndex(
            model_name='bill',
            name='tracker_bil_debated_932acb_idx',
        ),
        migrations.RemoveIndex(
            model_name='bill',
            name='tracker_bil_debated_235c8c_idx',
        ),
        migrations.AlterField(
            model_name='bill',
            name='act_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bill',
            name='act_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='assent_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('GOVERNMENT', 'Government Bill'), ('PRIVATE', 'Private Member Bill'), ('FINANCE', 'Finance Bill'), ('CONSTITUTION', 'Constitution Amendment Bill')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='bill',
            name='committee_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='bill',
            name='committee_report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='debated_on_ls_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='debated_on_rs_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='gazette_notification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='gazette_notification_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bill',
            name='introduced_by_mp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_introduced', to='tracker.mp'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='legislative_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='originating_house',
            field=models.CharField(blank=True, choices=[('LOK_SABHA', 'Lok Sabha'), ('RAJYA_SABHA', 'Rajya Sabha')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bill',
            name='referred_to_committee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['introduced_by_mp'], name='tracker_bil_introdu_969d19_idx'),
        ),
    ]
