# Generated by Django 6.0.2 on 2026-04-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_remove_bill_tracker_bil_origina_d2f147_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bill',
            name='tracker_bil_state_d8ee96_idx',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_number_display',
            field=models.CharField(blank=True, help_text='Bill number as displayed (e.g., Bill No. 1 of 2026)', max_length=50),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_series',
            field=models.CharField(blank=True, help_text='Bill series (e.g., C, G, P)', max_length=20),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_year',
            field=models.IntegerField(blank=True, help_text='Year from bill number (e.g., 2026 from Bill No. 1 of 2026)', null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='is_government_bill',
            field=models.BooleanField(default=True, help_text='True for Government Bill, False for Private Member Bill'),
        ),
        migrations.AddField(
            model_name='bill',
            name='member_name',
            field=models.CharField(blank=True, help_text='Member who introduced the bill (from Sansad data)', max_length=200),
        ),
        migrations.AddField(
            model_name='bill',
            name='referred_to_committee_date',
            field=models.DateField(blank=True, help_text='Date referred to committee', null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='sansad_link',
            field=models.URLField(blank=True, help_text='Link to Sansad website bill page', max_length=500),
        ),
        migrations.AddField(
            model_name='bill',
            name='status_display',
            field=models.CharField(blank=True, help_text='Status as displayed on Sansad website', max_length=100),
        ),
        migrations.AlterField(
            model_name='bill',
            name='act_number',
            field=models.CharField(blank=True, help_text='Act number after presidential assent', max_length=50),
        ),
        migrations.AlterField(
            model_name='bill',
            name='assent_date',
            field=models.DateField(blank=True, null=True, verbose_name='Assent Date'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='committee_name',
            field=models.CharField(blank=True, help_text='Name of the committee', max_length=500),
        ),
        migrations.AlterField(
            model_name='bill',
            name='committee_report_date',
            field=models.DateField(blank=True, help_text='Date of committee report', null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='gazette_notification_date',
            field=models.DateField(blank=True, null=True, verbose_name='Gazette Notification Date'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='introduction_date',
            field=models.DateField(blank=True, help_text='Date of Introduction', null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='originating_house',
            field=models.CharField(blank=True, choices=[('LOK_SABHA', 'Lok Sabha'), ('RAJYA_SABHA', 'Rajya Sabha')], help_text='House where bill was first introduced', max_length=20),
        ),
        migrations.AlterField(
            model_name='bill',
            name='passed_in_ls_date',
            field=models.DateField(blank=True, null=True, verbose_name='Debate/Date Passed in Lok Sabha'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='passed_in_rs_date',
            field=models.DateField(blank=True, null=True, verbose_name='Debate/Date Passed in Rajya Sabha'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='short_title',
            field=models.CharField(blank=True, help_text='Short title of the bill', max_length=200),
        ),
        migrations.AlterField(
            model_name='bill',
            name='source',
            field=models.CharField(default='SANSAD', max_length=50),
        ),
        migrations.AlterField(
            model_name='scrapesource',
            name='source_type',
            field=models.CharField(choices=[('PRS', 'PRS India'), ('LOK_SABHA', 'Lok Sabha'), ('RAJYA_SABHA', 'Rajya Sabha'), ('DATA_GOV_IN', 'data.gov.in'), ('MPA', 'Ministry of Parliamentary Affairs'), ('SANSAD', 'Sansad Website')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['originating_house'], name='tracker_bil_origina_d2f147_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['bill_number'], name='tracker_bil_bill_nu_f4356b_idx'),
        ),
        migrations.RemoveField(
            model_name='bill',
            name='act_year',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='bill_url',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='debated_on_ls_date',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='debated_on_rs_date',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='introduced_in',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='passed_date',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='referred_to_committee',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='state',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='status_details',
        ),
    ]
