# Generated by Django 6.0.2 on 2026-04-25 18:07

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_remove_bill_tracker_bil_state_d8ee96_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='StateBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_id', models.CharField(max_length=50, unique=True)),
                ('bill_number', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=100)),
                ('legislative_assembly', models.CharField(max_length=200)),
                ('introduction_date', models.DateField(blank=True, null=True)),
                ('passed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('AWAITING_ASSENT', 'Awaiting Governor/President Assent'), ('ENACTED', 'Enacted')], default='PENDING', max_length=50)),
                ('key_features', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('introduced_by', models.CharField(blank=True, max_length=200)),
                ('ministry', models.CharField(blank=True, max_length=200)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-introduction_date'],
                'indexes': [models.Index(fields=['state'], name='tracker_sta_state_2eeb93_idx'), models.Index(fields=['status'], name='tracker_sta_status_386170_idx'), models.Index(fields=['introduction_date'], name='tracker_sta_introdu_09e416_idx')],
            },
        ),
    ]
